version: 0.18.{build}
environment:
  BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=7
configuration: Release
platform:
- x86
- x64
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
branches:
  except:
  - gh-pages
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
  - platform: x86
    configuration: Release
  - platform: x64
    configuration: Release
cache:
- packages -> **\packages.config
before_build:
- appveyor-retry nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: Fasetto.Word\bin\$(platform)\$(configuration)\
  name: Fasetto.Word-v$(appveyor_build_version)-$(platform)
  type: zip
deploy:
- provider: GitHub
  tag: Fasetto.Word-v$(appveyor_build_version)
  description: Fasetto.Word Version $(appveyor_build_version)
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master
