version: 0.15.{build}
environment:
  BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=7
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  appveyor_rdp_password:
    secure: y6+0kl3pd9B+Nu4usCJngQ==
skip_tags: true
init:
  - git config --global core.autocrlf input
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
branches:
  # blacklist
  except:
    - gh-pages
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release
install:
  - appveyor-retry choco install doxygen.portable graphviz.portable
cache:
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml
 - c:\python36\lib\site-packages -> appveyor.yml
 - packages -> **\packages.config
before_build:
  appveyor-retry nuget restore
after_build:
  - appveyor-retry pip install sphinx sphinx-autobuild recommonmark
  - cd C:\Projects\fasseto-word\doc
  - doxygen.exe "..\Fasetto.Word.Doxyfile"
  - make html
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: minimal
artifacts:
  - path: Fasetto.Word\bin\$(platform)\$(configuration)\
    name: Fasetto.Word-v$(appveyor_build_version)-$(platform)
    type: zip
  - path: doc\_build\html
    name: Fasseto.Word.Docs-${platform}
    type: zip
deploy:
- provider: GitHub
  tag: Fasetto.Word-v$(appveyor_build_version)
  description: Fasetto.Word Version $(appveyor_build_version)
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
  - more "%USERPROFILE%\.git-credentials"
  - git config --global user.email "mitoskalandiel@gmail.com"
  - git config --global user.name "Mitos Kalandiel"
  - cd C:\Projects\fasseto-word\doc
  - git add -A --ignore-removal .
  - git commit -a -m "Added updated docs from doxygen/sphinx for version $($env:appveyor_build_version)"
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git push origin ${APPVEYOR_REPO_BRANCH}